/**
 * Generated API Types
 * 
 * Auto-generated from OpenAPI specification
 * Do not edit this file manually - it will be overwritten
 */

export interface HealthResponse {
  status: string;
  timestamp: string;
  service: string;
}

export interface Position {
  address: string;
  healthFactor: string;
  totalCollateralETH: string;
  totalDebtETH: string;
  isAtRisk: boolean;
}

export interface PositionsResponse {
  positions: Position[];
  count: number;
  timestamp: string;
}

export interface ProtectRequest {
  userAddress: string;
  protectionType?: 'REFINANCE' | 'EMERGENCY';
}

export interface ProtectResponse {
  status: string;
  requestId: string;
  userAddress: string;
  protectionType: string;
  timestamp: string;
}

export interface ErrorResponse {
  error: string;
}

export type ApiRoutes = {
  '/api/v1/health': {
    GET: {
      response: HealthResponse;
    };
  };
  '/api/v1/positions': {
    GET: {
      response: PositionsResponse;
    };
  };
  '/api/v1/protect': {
    POST: {
      body: ProtectRequest;
      response: ProtectResponse;
    };
  };
};
