#!/usr/bin/env tsx
/**
 * API Type Generation Script
 * Generates TypeScript type definitions from OpenAPI spec
 * 
 * Note: This is a stub implementation that creates a placeholder file.
 * In production, you would use tools like:
 * - openapi-typescript
 * - swagger-typescript-api
 * - openapi-generator
 */

import { writeFileSync, existsSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const outputPath = resolve(__dirname, '../src/types/api.d.ts');

// Ensure directory exists
const dir = dirname(outputPath);
if (!existsSync(dir)) {
  mkdirSync(dir, { recursive: true });
}

const typeDefinitions = `/**
 * Generated API Types
 * 
 * Auto-generated from OpenAPI specification
 * Do not edit this file manually - it will be overwritten
 */

export interface HealthResponse {
  status: string;
  timestamp: string;
  service: string;
}

export interface Position {
  address: string;
  healthFactor: string;
  totalCollateralETH: string;
  totalDebtETH: string;
  isAtRisk: boolean;
}

export interface PositionsResponse {
  positions: Position[];
  count: number;
  timestamp: string;
}

export interface ProtectRequest {
  userAddress: string;
  protectionType?: 'REFINANCE' | 'EMERGENCY';
}

export interface ProtectResponse {
  status: string;
  requestId: string;
  userAddress: string;
  protectionType: string;
  timestamp: string;
}

export interface ErrorResponse {
  error: string;
}

export type ApiRoutes = {
  '/api/v1/health': {
    GET: {
      response: HealthResponse;
    };
  };
  '/api/v1/positions': {
    GET: {
      response: PositionsResponse;
    };
  };
  '/api/v1/protect': {
    POST: {
      body: ProtectRequest;
      response: ProtectResponse;
    };
  };
};
`;

console.log('📝 Generating API types...');
writeFileSync(outputPath, typeDefinitions, 'utf-8');
console.log(`✅ API types generated successfully: ${outputPath}`);
